### ISSUE TITLE
scene/turn_off. Service not found

### ISSUE THREAD

**Issue by bonepl** [jheling/freeathome#106]
I have several scenes created in free@home, but activating scene entities fetched by integration ends up with message "Couldn't trigger service scene/turn_off. Service not found".

I updated free@home sysap firmware recently and moved to new mobile app Free@Home Next. Could this break this part of integration?

**Comment by jheling** [comment]
Hello,  that could be a cause of your problems. I have not yet tried the new app. Can you still use both apps?
On what firmware version are you now?

**Comment by Tho85** [comment]
How exactly do you trigger the scenes? It looks like you try to call a service `scene/turn_off`. If I read the docs correctly, this service does not exist in Home Assistant (you can't turn off a scene, only turn on). Have you tried using the service`scene.turn_on`?

**Comment by bonepl** [comment]
I just updated today to firmware version 2.6.4 from [SAP-S-2 | ABB](https://new.abb.com/products/2CKA006200A0105/sap-s-2), problem still persist.

I enabled integration and added scene as a button:
```
type: button
tap_action:
  action: toggle
entity: scene.turn_off_all
name: Turn off all
```

Not sure how to change the usage of the service to `scene.turn_on`.

**Comment by Tho85** [comment]
I use it like this:
```yaml
type: button
tap_action:
  action: call-service
  service: scene.turn_on
  service_data:
    entity_id: scene.my_scene
entity: scene.my_scene
```
