### ISSUE TITLE
Cant use wall-buttons to start automation

### ISSUE THREAD

**Issue by hnktnk** [jheling/freeathome#123]
Hi!

I'm trying to use a wallswitch in my f@h setup to activate an automation. This button is a sceneactivator i  f@h which I think works different than if its just a "button". I might be wrong but to eliminate this thought, I'm trying another switch in my house.

I have recorded the service in HA which gave me thix XML-line:
`<?xml version="1.0" encoding="UTF-8"?><project timeStamp="273367" sessionId="4b171115" type="update" mrhaVersion="2.6.4" mrhaBuild="8172"><privileges/><devices><device serialNumber="ABB700CE5B0F" domainAddress="5036" state="modified" commissioningState="ready" progress="100"><channels><channel state="modified" i="ch0002" cid="ABB70068"><inputs/><outputs><dataPoint state="modified" i="odp0000" full="false"><value>0</value></dataPoint></outputs><parameters/><scenes/></channel></channels><parameters/></device></devices></project>`

From this I set my automation trigger event to:
```
  trigger:
  - platform: event
    event_type: freeathome_event
    event_data:
      unique_id: ABB700CE5B0F/ch0002
      command: pressed
      state: true
```
Then I added a simple action, to turn off a light in a room via HA. Now, saving this automation and pressing the wallswitch does nothing. Running the automation works fine, it turns the light off so something is off getting the switch-event?
Complete automation code:
```
- id: '1642939951688'
  alias: Byebye
  description: ''
  trigger:
  - platform: event
    event_type: freeathome_event
    event_data:
      unique_id: ABB700CE5B0F/ch0002
      command: pressed
      state: true
  condition: []
  action:
  - service: media_player.turn_off
    target:
      device_id:
      - c7def65aeac448a8a6902e2dd753f8ca
      - 5b81054caa2073aa20c977564318e2ea
  - service: light.turn_off
    target:
      entity_id: light.takbel_kontor
  mode: single
```
I'll fix a dump a little bit later.
