### ISSUE TITLE
Scenes not working with Tilt Position 0 and 100

### ISSUE THREAD

**Issue by Tau-Neutrino** [jheling/freeathome#124]
Hello,

I found an issue with scenens created via HomeAssistant.

It seems like changes of cover tilt (did not test position until now) are not executed if the value is 0 or 100. 
A workaround for now is to manually edit the yaml and replace 0,100 by 1,99 !

**Not working** examples:
```
entities:
    cover.z1_s:
        current_position: 0
        current_tilt_position: 0

entities:
    cover.z1_s:
        current_position: 0
        current_tilt_position: 100
```

**Working** examples:
```
entities:
    cover.z1_s:
        current_position: 0
        current_tilt_position: 1

entities:
    cover.z1_s:
        current_position: 0
        current_tilt_position: 99
```
