### ISSUE TITLE
FEATURE: Current Temperature from Thermostat as Sensor

### ISSUE THREAD

**Issue by fahhome123** [jheling/freeathome#129]
Hi Heling and Supporters,

great work. 
I tried to extract the current temperature from thermostat entity as Sensor information without luck.
Can you do this please? 

It is usefull to know how degree is it.

The information exists but how can this added as Sensor entity.

thanks. 
regards

**Comment by fahhome123** [comment]
Hi, I doen't know how I can do it.
But I find, that the information for this is on

PID_MEASURED_TEMPERATURE = 0x0130

So, it should be better for all when we do this directly in this addon.

**Comment by fahhome123** [comment]
@EnricoBilla: I can try to get the current temperature from thermostat entity. I look it too.

**Comment by derjoerg** [comment]
Hi,

as stated by @EnricoBilla this should be possible with a sensor template.
Put something like that in your configuration.yaml

```
template:
  - sensor:
    - name: "Current Temperature"
      unit_of_measurement: "°C"
      state: "{{ '%.1f'|format(state_attr('climate.raumtemperaturregler_xyz', 'current_temperature')) }}"
```
