### ISSUE TITLE
room temperature controler - no percentageand heating state

### ISSUE THREAD

**Issue by mattberlinHA** [jheling/freeathome#156]
Hi guys,

there is a percentage being determined by the room temperature controllers. This percentage then acts on the heating actuators.
This value does not seem to be availble with this integration (with openHAB it seems to be there).
Can this also be done with this integration?

**Comment by Tho85** [comment]
The value is available as a state attribute:
![grafik](https://user-images.githubusercontent.com/22068/218667418-cc9654e0-3f66-4f13-a3bb-f2fc9b194424.png)

You can use it in a [template sensor](https://www.home-assistant.io/integrations/template/) like this:

```yaml
template:
    sensor:
      - name: "RTC valve"
        state: '{{ state_attr("climate.rtr_ab_ab", "valve") }}'
        unit_of_measurement: "%"
```
